project:
  type: website
  output-dir: docs
  render:
   - index.qmd
   - exercises/index.qmd
   - about.qmd

website:
  site-url: "https://emitanaka.org/dataviz-workshop/"
  repo-url: "https://github.com/emitanaka/dataviz-workshop"
  title: "Data Visualisation with R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/index.qmd
        text: Exercises
      - about.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-after: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.1.1-web/css/all.min.css">
      <script src="/assets/fontawesome-free-6.1.1-web/js/all.min.js"></script>

